/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import kelas.Car;
import kelas.Toyota;
import kelas.Honda;
import kelas.Suzuki;
import kelas.Daihatsu;
import kelas.KIA;
import kelas.Mazda;
import kelas.Mitsubishi;
import kelas.Nissan;

/**
 *
 * @author Amalia
 */
public class Dashboard extends javax.swing.JFrame {
    private int x;
    private int y;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        this.setLocationRelativeTo(null); // center form in the screen
        this.setResizable(false); // prevent frame from being resized
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardBtn = new javax.swing.JLabel();
        historyBtn = new javax.swing.JLabel();
        closeBtn = new javax.swing.JLabel();
        minimizeBtn = new javax.swing.JLabel();
        profileBtn = new javax.swing.JLabel();
        toyotaBtn = new javax.swing.JLabel();
        suzukiBtn = new javax.swing.JLabel();
        hondaBtn = new javax.swing.JLabel();
        daihatsuBtn = new javax.swing.JLabel();
        mitsubishiBtn = new javax.swing.JLabel();
        nissanBtn = new javax.swing.JLabel();
        kiaBtn = new javax.swing.JLabel();
        mazdaBtn = new javax.swing.JLabel();
        panel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardBtnMouseClicked(evt);
            }
        });
        getContentPane().add(dashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 160, 50));

        historyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyBtnMouseClicked(evt);
            }
        });
        getContentPane().add(historyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 120, 50));

        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(767, 0, 20, 30));

        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(minimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 0, 20, 30));

        profileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileBtnMouseClicked(evt);
            }
        });
        getContentPane().add(profileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 40, 60));

        toyotaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toyotaBtnMouseClicked(evt);
            }
        });
        getContentPane().add(toyotaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 90, 100));

        suzukiBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suzukiBtnMouseClicked(evt);
            }
        });
        getContentPane().add(suzukiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 100, 100));

        hondaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hondaBtnMouseClicked(evt);
            }
        });
        getContentPane().add(hondaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 100, 100));

        daihatsuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daihatsuBtnMouseClicked(evt);
            }
        });
        getContentPane().add(daihatsuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 100, 100));

        mitsubishiBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mitsubishiBtnMouseClicked(evt);
            }
        });
        getContentPane().add(mitsubishiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 100, 100));

        nissanBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nissanBtnMouseClicked(evt);
            }
        });
        getContentPane().add(nissanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 100, 100));

        kiaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kiaBtnMouseClicked(evt);
            }
        });
        getContentPane().add(kiaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 100, 100));

        mazdaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mazdaBtnMouseClicked(evt);
            }
        });
        getContentPane().add(mazdaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 100, 100));

        panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard.png"))); // NOI18N
        panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelMouseDragged(evt);
            }
        });
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMousePressed(evt);
            }
        });
        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMousePressed
        this.x = evt.getX();
        this.y = evt.getY();
    }//GEN-LAST:event_panelMousePressed

    private void panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseDragged
        int x1 = evt.getXOnScreen();
        int y1 = evt.getYOnScreen();
        
        this.setLocation(x1-x, y1-y);
    }//GEN-LAST:event_panelMouseDragged

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        this.setExtendedState(Dashboard.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void dashboardBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardBtnMouseClicked
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardBtnMouseClicked

    private void historyBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyBtnMouseClicked
        History history = new History();
        history.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_historyBtnMouseClicked

    private void profileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnMouseClicked
        Profile profile = new Profile();
        profile.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profileBtnMouseClicked

    private void toyotaBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toyotaBtnMouseClicked
        Car toyota = new Toyota();
        List list = new List();
        toyota.listCar(list);
        list.setVisible(true);
        this.dispose();    
    }//GEN-LAST:event_toyotaBtnMouseClicked

    private void suzukiBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suzukiBtnMouseClicked
        Car suzuki = new Suzuki();
        List list = new List();
        suzuki.listCar(list);
        list.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_suzukiBtnMouseClicked

    private void hondaBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hondaBtnMouseClicked
        Car honda = new Honda();
        List list = new List();
        honda.listCar(list);
        list.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hondaBtnMouseClicked

    private void daihatsuBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daihatsuBtnMouseClicked
        Car daihatsu = new Daihatsu();
        List list = new List();
        daihatsu.listCar(list);
        list.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_daihatsuBtnMouseClicked

    private void mitsubishiBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mitsubishiBtnMouseClicked
        Car mitsubishi = new Mitsubishi();
        List list = new List();
        mitsubishi.listCar(list);
        list.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mitsubishiBtnMouseClicked

    private void nissanBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nissanBtnMouseClicked
        Car nissan = new Nissan();
        List list = new List();
        nissan.listCar(list);
        list.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nissanBtnMouseClicked

    private void kiaBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kiaBtnMouseClicked
        Car kia = new KIA();
        List list = new List();
        kia.listCar(list);
        list.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kiaBtnMouseClicked

    private void mazdaBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mazdaBtnMouseClicked
        Car mazda = new Mazda();
        List list = new List();
        mazda.listCar(list);
        list.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mazdaBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeBtn;
    private javax.swing.JLabel daihatsuBtn;
    private javax.swing.JLabel dashboardBtn;
    private javax.swing.JLabel historyBtn;
    private javax.swing.JLabel hondaBtn;
    private javax.swing.JLabel kiaBtn;
    private javax.swing.JLabel mazdaBtn;
    private javax.swing.JLabel minimizeBtn;
    private javax.swing.JLabel mitsubishiBtn;
    private javax.swing.JLabel nissanBtn;
    private javax.swing.JLabel panel;
    private javax.swing.JLabel profileBtn;
    private javax.swing.JLabel suzukiBtn;
    private javax.swing.JLabel toyotaBtn;
    // End of variables declaration//GEN-END:variables
}
