/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import kelas.Car;
import kelas.Daihatsu;
import kelas.Datauser;
import kelas.Honda;
import kelas.KIA;
import kelas.Mazda;
import kelas.Mitsubishi;
import kelas.Nissan;
import kelas.Suzuki;
import kelas.Toyota;

/**
 *
 * @author Amalia
 */
public class Detail extends javax.swing.JFrame {
    private int x;
    private int y;
    private ImageIcon format = null;
    private String jenis;
    /**
     * Creates new form Detail
     */
    public Detail() {
        initComponents();
        this.setLocationRelativeTo(null); // center form in the screen
        this.setResizable(false); // prevent frame from being resized
    }
    
    public void setDetail(String jenis, String model, String ukuran, String pemilik, String hp_pemilik){
        this.jenis = jenis;
        modelTxt.setText(model);
        ukuranTxt.setText(ukuran);
        pemilikTxt.setText(pemilik);
        hpemilikTxt.setText(hp_pemilik);
    }
    
    public void setDetail(int harga) {
        hargaTxt.setText(Integer.toString(harga));
    }
    
    public void setDetail(byte[] gambar) {
        format = new ImageIcon(gambar);
        Image mm = format.getImage();
        int width = mobilFoto.getWidth();
        int height = mobilFoto.getHeight();
        Image img2 = mm.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        mobilFoto.setIcon(image);
    }
    
    public void setAllDetails(String jenis, String model, String ukuran, String pemilik, String hp_pemilik, int harga, byte[] gambar) {
        setDetail(jenis, model, ukuran, pemilik, hp_pemilik);
        setDetail(harga);
        setDetail(gambar);
        this.setVisible(true);
    }
    
    public String getModel() {
        return modelTxt.getText();
    }
    
    public String getUkuran() {
        return ukuranTxt.getText();
    }
    
    public int getHarga() {
        return Integer.parseInt(hargaTxt.getText());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeBtn = new javax.swing.JLabel();
        minimizeBtn = new javax.swing.JLabel();
        mobilFoto = new javax.swing.JLabel();
        backBtn = new javax.swing.JLabel();
        dashboardBtn = new javax.swing.JLabel();
        historyBtn = new javax.swing.JLabel();
        profileBtn = new javax.swing.JLabel();
        bookingBtn = new javax.swing.JLabel();
        downloadBtn = new javax.swing.JLabel();
        modelTxt = new javax.swing.JLabel();
        ukuranTxt = new javax.swing.JLabel();
        hargaTxt = new javax.swing.JLabel();
        pemilikTxt = new javax.swing.JLabel();
        hpemilikTxt = new javax.swing.JLabel();
        panel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 20, 30));

        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(minimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 20, 30));
        getContentPane().add(mobilFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 170, 180));

        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 46, 30, 40));

        dashboardBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardBtnMouseClicked(evt);
            }
        });
        getContentPane().add(dashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 150, 50));

        historyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyBtnMouseClicked(evt);
            }
        });
        getContentPane().add(historyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 120, 40));

        profileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileBtnMouseClicked(evt);
            }
        });
        getContentPane().add(profileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 60, 60));

        bookingBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingBtnMouseClicked(evt);
            }
        });
        getContentPane().add(bookingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 120, 40));

        downloadBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                downloadBtnMouseClicked(evt);
            }
        });
        getContentPane().add(downloadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 40, 40));

        modelTxt.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        getContentPane().add(modelTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 250, 10));

        ukuranTxt.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        getContentPane().add(ukuranTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 360, 260, 30));

        hargaTxt.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        getContentPane().add(hargaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 140, 20));

        pemilikTxt.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        getContentPane().add(pemilikTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 260, 20));

        hpemilikTxt.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        getContentPane().add(hpemilikTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 250, 20));

        panel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Detail.png"))); // NOI18N
        panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelMouseDragged(evt);
            }
        });
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMousePressed(evt);
            }
        });
        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMousePressed
        this.x = evt.getX();
        this.y = evt.getY();
    }//GEN-LAST:event_panelMousePressed

    private void panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseDragged
        int x1 = evt.getXOnScreen();
        int y1 = evt.getYOnScreen();
        
        this.setLocation(x1-x, y1-y);
    }//GEN-LAST:event_panelMouseDragged

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        this.setExtendedState(Detail.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        List list = new List();
        if(jenis.equals("Toyota")) {
            Car toyota = new Toyota();
            toyota.listCar(list);
        } else if(jenis.equals("Suzuki")) {
            Car suzuki = new Suzuki();        
            suzuki.listCar(list);
        } else if(jenis.equals("Honda")) {
            Car honda = new Honda();        
            honda.listCar(list);
        } else if(jenis.equals("Daihatsu")) {
            Car daihatsu = new Daihatsu();
            daihatsu.listCar(list);
        } else if(jenis.equals("Mitsubishi")) {
            Car mitsubishi = new Mitsubishi();
            mitsubishi.listCar(list);
        } else if(jenis.equals("Nissan")) {
            Car nissan = new Nissan();
            nissan.listCar(list);
        } else if(jenis.equals("KIA")) {
            Car kia = new KIA();
            kia.listCar(list);
        } else if(jenis.equals("Mazda")) {
            Car mazda = new Mazda();
            mazda.listCar(list);
        }
        list.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnMouseClicked

    private void dashboardBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardBtnMouseClicked
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardBtnMouseClicked

    private void historyBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyBtnMouseClicked
        History history = new History();
        history.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_historyBtnMouseClicked

    private void profileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnMouseClicked
        Profile profile = new Profile();
        profile.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profileBtnMouseClicked

    private void bookingBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingBtnMouseClicked
        Done done = new Done();
        if(jenis.equals("Toyota")) {
            Car toyota = new Toyota();
            Datauser user = new Datauser(toyota);
            user.bookingCar(this);            
        } else if(jenis.equals("Suzuki")) {
            Car suzuki = new Suzuki();
            Datauser user = new Datauser(suzuki);
            user.bookingCar(this); 
        } else if(jenis.equals("Honda")) {
            Car honda = new Honda();
            Datauser user = new Datauser(honda);
            user.bookingCar(this);
        } else if(jenis.equals("Daihatsu")) {
            Car daihatsu = new Daihatsu();
            Datauser user = new Datauser(daihatsu);
            user.bookingCar(this);
        } else if(jenis.equals("Mitsubishi")) {
            Car mitsubishi = new Mitsubishi();
            Datauser user = new Datauser(mitsubishi);
            user.bookingCar(this);
        } else if(jenis.equals("Nissan")) {
            Car nissan = new Nissan();
            Datauser user = new Datauser(nissan);
            user.bookingCar(this);
        } else if(jenis.equals("KIA")) {
            Car kia = new KIA();
            Datauser user = new Datauser(kia);
            user.bookingCar(this);
        } else if(jenis.equals("Mazda")) {
            Car mazda = new Mazda();
            Datauser user = new Datauser(mazda);
            user.bookingCar(this);
        }
        done.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bookingBtnMouseClicked

    private void downloadBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downloadBtnMouseClicked
        BufferedImage image = new BufferedImage(mobilFoto.getWidth(), mobilFoto.getHeight(), BufferedImage.TYPE_INT_ARGB);
        Graphics g = image.getGraphics();
        mobilFoto.paint(g);
        try {
            ImageIO.write(image, "png", new File("D:\\image.png"));
            System.out.println("Image saved successfully.");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_downloadBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backBtn;
    private javax.swing.JLabel bookingBtn;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JLabel dashboardBtn;
    private javax.swing.JLabel downloadBtn;
    private javax.swing.JLabel hargaTxt;
    private javax.swing.JLabel historyBtn;
    private javax.swing.JLabel hpemilikTxt;
    private javax.swing.JLabel minimizeBtn;
    private javax.swing.JLabel mobilFoto;
    private javax.swing.JLabel modelTxt;
    private javax.swing.JLabel panel;
    private javax.swing.JLabel pemilikTxt;
    private javax.swing.JLabel profileBtn;
    private javax.swing.JLabel ukuranTxt;
    // End of variables declaration//GEN-END:variables
}
