/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import kelas.Databases;

/**
 *
 * @author Amalia
 */
public class List extends javax.swing.JFrame {
    private int x;
    private int y;
    private ArrayList<JLabel> listLabels = new ArrayList<>();
    private ArrayList<JLabel> jenisLabels = new ArrayList<>();
    /**
     * Creates new form List
     */
    public List() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        // Inisialisasi array list dan jenis
        // Inisialisasi array dengan panjang yang sesuai
        listLabels.add(list1);
        listLabels.add(list2);
        listLabels.add(list3);
        listLabels.add(list4);
        listLabels.add(list5);
        listLabels.add(list6);

        jenisLabels.add(jenis1);
        jenisLabels.add(jenis2);
        jenisLabels.add(jenis3);
        jenisLabels.add(jenis4);
        jenisLabels.add(jenis5);
        jenisLabels.add(jenis6);
    }

    public void setList(ArrayList<ImageIcon> imageIcons, ArrayList<String> models) {
        for (int i = 0; i < models.size(); i++) {
            listLabels.get(i).setIcon(imageIcons.get(i));
            jenisLabels.get(i).setText(models.get(i));
        }
        this.setVisible(true);
    }

    public ArrayList<JLabel> getList() {
        return listLabels;
    }

    public ArrayList<JLabel> getJenis() {
        return jenisLabels;
    }
    
    public static String getWords(String input) {
        String[] words = input.split(" ");
        int length = words.length;

        if (length == 2) {
            return words[length - 1];
        } else if (length >= 3) {
            return words[length - 2] + " " + words[length - 1];
        } else {
            return "";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeBtn = new javax.swing.JLabel();
        minimizeBtn = new javax.swing.JLabel();
        backBtn = new javax.swing.JLabel();
        dashboardBtn = new javax.swing.JLabel();
        historyBtn = new javax.swing.JLabel();
        profileBtn = new javax.swing.JLabel();
        list1 = new javax.swing.JLabel();
        list2 = new javax.swing.JLabel();
        list3 = new javax.swing.JLabel();
        list6 = new javax.swing.JLabel();
        list5 = new javax.swing.JLabel();
        list4 = new javax.swing.JLabel();
        jenis1 = new javax.swing.JLabel();
        jenis2 = new javax.swing.JLabel();
        jenis3 = new javax.swing.JLabel();
        jenis4 = new javax.swing.JLabel();
        jenis5 = new javax.swing.JLabel();
        jenis6 = new javax.swing.JLabel();
        panel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 20, 30));

        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(minimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 20, 30));

        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 40, 30));

        dashboardBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardBtnMouseClicked(evt);
            }
        });
        getContentPane().add(dashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 150, 50));

        historyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyBtnMouseClicked(evt);
            }
        });
        getContentPane().add(historyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 120, 50));

        profileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileBtnMouseClicked(evt);
            }
        });
        getContentPane().add(profileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 40, 40));

        list1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list1MouseClicked(evt);
            }
        });
        getContentPane().add(list1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 130, 110));

        list2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list2MouseClicked(evt);
            }
        });
        getContentPane().add(list2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 130, 110));

        list3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list3MouseClicked(evt);
            }
        });
        getContentPane().add(list3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 130, 110));

        list6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list6MouseClicked(evt);
            }
        });
        getContentPane().add(list6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 130, 100));

        list5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list5MouseClicked(evt);
            }
        });
        getContentPane().add(list5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 130, 100));

        list4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list4MouseClicked(evt);
            }
        });
        getContentPane().add(list4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 130, 110));

        jenis1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jenis1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jenis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 130, 20));

        jenis2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jenis2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jenis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 130, 20));

        jenis3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jenis3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jenis3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 130, 20));

        jenis4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jenis4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jenis4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 130, 20));

        jenis5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jenis5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jenis5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 130, 20));

        jenis6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jenis6.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jenis6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 130, 20));

        panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/List.png"))); // NOI18N
        panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelMouseDragged(evt);
            }
        });
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMousePressed(evt);
            }
        });
        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        this.setExtendedState(List.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnMouseClicked

    private void dashboardBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardBtnMouseClicked
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardBtnMouseClicked

    private void historyBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyBtnMouseClicked
        History history = new History();
        history.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_historyBtnMouseClicked

    private void profileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnMouseClicked
        Profile profile = new Profile();
        profile.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profileBtnMouseClicked

    private void list1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list1MouseClicked
        String input = jenis1.getText();
        String model = getWords(input);
        Detail detail = new Detail();
        Databases databases = new Databases();
        databases.detailCar(detail, model);
        detail.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_list1MouseClicked

    private void list2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list2MouseClicked
        String input = jenis2.getText();
        String model = getWords(input);
        Detail detail = new Detail();
        Databases databases = new Databases();
        databases.detailCar(detail, model);
        detail.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_list2MouseClicked

    private void list3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list3MouseClicked
        String input = jenis3.getText();
        String model = getWords(input);
        Detail detail = new Detail();
        Databases databases = new Databases();
        databases.detailCar(detail, model);
        detail.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_list3MouseClicked

    private void list4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list4MouseClicked
        String input = jenis4.getText();
        String model = getWords(input);
        Detail detail = new Detail();
        Databases databases = new Databases();
        databases.detailCar(detail, model);
        detail.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_list4MouseClicked

    private void list5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list5MouseClicked
        String input = jenis5.getText();
        String model = getWords(input);
        Detail detail = new Detail();
        Databases databases = new Databases();
        databases.detailCar(detail, model);
        detail.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_list5MouseClicked

    private void list6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list6MouseClicked
        String input = jenis6.getText();
        String model = getWords(input);
        Detail detail = new Detail();
        Databases databases = new Databases();
        databases.detailCar(detail, model);
        detail.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_list6MouseClicked

    private void panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMousePressed
        this.x = evt.getX();
        this.y = evt.getY();
    }//GEN-LAST:event_panelMousePressed

    private void panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseDragged
        int x1 = evt.getXOnScreen();
        int y1 = evt.getYOnScreen();

        this.setLocation(x1-x, y1-y);
    }//GEN-LAST:event_panelMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backBtn;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JLabel dashboardBtn;
    private javax.swing.JLabel historyBtn;
    private javax.swing.JLabel jenis1;
    private javax.swing.JLabel jenis2;
    private javax.swing.JLabel jenis3;
    private javax.swing.JLabel jenis4;
    private javax.swing.JLabel jenis5;
    private javax.swing.JLabel jenis6;
    private javax.swing.JLabel list1;
    private javax.swing.JLabel list2;
    private javax.swing.JLabel list3;
    private javax.swing.JLabel list4;
    private javax.swing.JLabel list5;
    private javax.swing.JLabel list6;
    private javax.swing.JLabel minimizeBtn;
    private javax.swing.JLabel panel;
    private javax.swing.JLabel profileBtn;
    // End of variables declaration//GEN-END:variables

}
